/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as GestionIndexRouteImport } from './routes/gestion/index'
import { Route as AuthenticatedGestionAdminRouteImport } from './routes/_authenticated/gestion.admin'
import { Route as GestionReviewTokenRouteImport } from './routes/gestion/review.$token'
import { Route as AuthenticatedGestionAdminSubmissionsCampaignIdRouteImport } from './routes/_authenticated/gestion.admin_.submissions.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const GestionIndexRoute = GestionIndexRouteImport.update({
  id: '/gestion/',
  path: '/gestion/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionAdminRoute =
  AuthenticatedGestionAdminRouteImport.update({
    id: '/gestion/admin',
    path: '/gestion/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const GestionReviewTokenRoute = GestionReviewTokenRouteImport.update({
  id: '/gestion/review/$token',
  path: '/gestion/review/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGestionAdminSubmissionsCampaignIdRoute =
  AuthenticatedGestionAdminSubmissionsCampaignIdRouteImport.update({
    id: '/gestion/admin_/submissions/$campaignId',
    path: '/gestion/admin/submissions/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gestion/': typeof GestionIndexRoute
  '/gestion/admin': typeof AuthenticatedGestionAdminRoute
  '/gestion/review/$token': typeof GestionReviewTokenRoute
  '/gestion/admin/submissions/$campaignId': typeof AuthenticatedGestionAdminSubmissionsCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/gestion': typeof GestionIndexRoute
  '/gestion/admin': typeof AuthenticatedGestionAdminRoute
  '/gestion/review/$token': typeof GestionReviewTokenRoute
  '/gestion/admin/submissions/$campaignId': typeof AuthenticatedGestionAdminSubmissionsCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/gestion/': typeof GestionIndexRoute
  '/_authenticated/gestion/admin': typeof AuthenticatedGestionAdminRoute
  '/gestion/review/$token': typeof GestionReviewTokenRoute
  '/_authenticated/gestion/admin_/submissions/$campaignId': typeof AuthenticatedGestionAdminSubmissionsCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/gestion/'
    | '/gestion/admin'
    | '/gestion/review/$token'
    | '/gestion/admin/submissions/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/gestion'
    | '/gestion/admin'
    | '/gestion/review/$token'
    | '/gestion/admin/submissions/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/gestion/'
    | '/_authenticated/gestion/admin'
    | '/gestion/review/$token'
    | '/_authenticated/gestion/admin_/submissions/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  GestionIndexRoute: typeof GestionIndexRoute
  GestionReviewTokenRoute: typeof GestionReviewTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestion/': {
      id: '/gestion/'
      path: '/gestion'
      fullPath: '/gestion/'
      preLoaderRoute: typeof GestionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestion/admin': {
      id: '/_authenticated/gestion/admin'
      path: '/gestion/admin'
      fullPath: '/gestion/admin'
      preLoaderRoute: typeof AuthenticatedGestionAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/gestion/review/$token': {
      id: '/gestion/review/$token'
      path: '/gestion/review/$token'
      fullPath: '/gestion/review/$token'
      preLoaderRoute: typeof GestionReviewTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/gestion/admin_/submissions/$campaignId': {
      id: '/_authenticated/gestion/admin_/submissions/$campaignId'
      path: '/gestion/admin/submissions/$campaignId'
      fullPath: '/gestion/admin/submissions/$campaignId'
      preLoaderRoute: typeof AuthenticatedGestionAdminSubmissionsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGestionAdminRoute: typeof AuthenticatedGestionAdminRoute
  AuthenticatedGestionAdminSubmissionsCampaignIdRoute: typeof AuthenticatedGestionAdminSubmissionsCampaignIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGestionAdminRoute: AuthenticatedGestionAdminRoute,
  AuthenticatedGestionAdminSubmissionsCampaignIdRoute:
    AuthenticatedGestionAdminSubmissionsCampaignIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  GestionIndexRoute: GestionIndexRoute,
  GestionReviewTokenRoute: GestionReviewTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
